package generator

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"adhdbis-updater/scraper"
)

// FetchLatestVersion checks GitHub for the latest release tag.
func FetchLatestVersion() string {
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get("https://api.github.com/repos/nenadjokic/ADHDBiS/releases/latest")
	if err != nil {
		return ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return ""
	}
	var result struct {
		TagName string `json:"tag_name"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return ""
	}
	// Strip leading "v" if present
	tag := result.TagName
	if len(tag) > 0 && tag[0] == 'v' {
		tag = tag[1:]
	}
	return tag
}

// luaEscape escapes a string for safe embedding in Lua source.
func luaEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}

// writeGearItem writes a single gear item entry to the string builder.
func writeGearItem(sb *strings.Builder, item scraper.GearItem, indent string) {
	sb.WriteString(fmt.Sprintf("%s{ slot = \"%s\", itemID = %d, name = \"%s\", source = \"%s\", bonusIDs = \"%s\", ilvl = %d",
		indent, luaEscape(item.Slot), item.ItemID, luaEscape(item.Name), luaEscape(item.Source), luaEscape(item.BonusIDs), item.Ilvl))
	if len(item.TooltipLines) > 0 {
		sb.WriteString(", tooltip = { ")
		for j, line := range item.TooltipLines {
			if j > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("\"%s\"", luaEscape(line)))
		}
		sb.WriteString(" }")
	}
	sb.WriteString(" },\n")
}

// Known embellishment itemIDs - these are optional reagents, not armor pieces.
// They should be listed in the enchants section, not in gear.
var embellishmentIDs = map[int]bool{
	240167: true, // Arcanoweave Lining
}

// isEmbellishment checks if a gear item is actually an embellishment.
func isEmbellishment(item scraper.GearItem) bool {
	return embellishmentIDs[item.ItemID]
}

// filterEmbellishments removes embellishments from a gear list and returns them separately.
func filterEmbellishments(gear []scraper.GearItem) (filtered []scraper.GearItem, embellishments []scraper.GearItem) {
	for _, item := range gear {
		if isEmbellishment(item) {
			embellishments = append(embellishments, item)
		} else {
			filtered = append(filtered, item)
		}
	}
	return
}

// embellishmentsToEnchants converts embellishment gear items to enchant entries.
func embellishmentsToEnchants(embellishments []scraper.GearItem) []scraper.EnchantItem {
	seen := map[int]bool{}
	var result []scraper.EnchantItem
	for _, item := range embellishments {
		if seen[item.ItemID] {
			continue // only add each embellishment once
		}
		seen[item.ItemID] = true
		result = append(result, scraper.EnchantItem{
			Slot:   "Embellishment",
			ItemID: item.ItemID,
			Name:   item.Name,
		})
	}
	return result
}

// GenerateLua creates ADHDBiS_Data.lua from scraped data and writes it to the AddOns folder.
// CompanionVersion is set by the caller (main.go)
var CompanionVersion = "1.6"

func GenerateLua(allData map[string]map[string]map[string]*scraper.SpecData, addOnsPath string, source string) error {
	var sb strings.Builder

	sb.WriteString("-- ADHDBiS Data: Best in Slot lists for all classes\n")
	sb.WriteString(fmt.Sprintf("-- Generated by ADHDBiS Updater on %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("-- Source: %s\n\n", source))

	// Check GitHub for latest addon version
	latestVer := FetchLatestVersion()

	sb.WriteString("ADHDBiS_Data = {\n")
	sb.WriteString(fmt.Sprintf("    version = \"%s\",\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("    generatedAt = \"%s\",\n", time.Now().UTC().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("    source = \"%s\",\n", luaEscape(source)))
	if latestVer != "" {
		sb.WriteString(fmt.Sprintf("    latestAddonVersion = \"%s\",\n", luaEscape(latestVer)))
	}
	sb.WriteString(fmt.Sprintf("    companionVersion = \"%s\",\n", luaEscape(CompanionVersion)))
	sb.WriteString("    classes = {\n")

	for className, specs := range allData {
		sb.WriteString(fmt.Sprintf("        [\"%s\"] = {\n", luaEscape(className)))

		for specName, sources := range specs {
			sb.WriteString(fmt.Sprintf("            [\"%s\"] = {\n", luaEscape(specName)))

			for sourceName, data := range sources {
				sb.WriteString(fmt.Sprintf("                [\"%s\"] = {\n", luaEscape(sourceName)))

				// Timestamps
				if data.ScrapedAt != "" {
					sb.WriteString(fmt.Sprintf("                    scrapedAt = \"%s\",\n", luaEscape(data.ScrapedAt)))
				}
				if data.SourceLastModified != "" {
					sb.WriteString(fmt.Sprintf("                    sourceLastModified = \"%s\",\n", luaEscape(data.SourceLastModified)))
				}

				// Stat Priority
				if data.StatPriority != "" {
					sb.WriteString(fmt.Sprintf("                    statPriority = \"%s\",\n", luaEscape(data.StatPriority)))
				}

				// Filter embellishments from gear lists -> move to enchants
				var allEmbellishments []scraper.GearItem
				overallGear, emb := filterEmbellishments(data.OverallGear)
				allEmbellishments = append(allEmbellishments, emb...)
				raidGear, emb := filterEmbellishments(data.RaidGear)
				allEmbellishments = append(allEmbellishments, emb...)
				mythicGear, emb := filterEmbellishments(data.MythicGear)
				allEmbellishments = append(allEmbellishments, emb...)

				// Gear (without embellishments)
				sb.WriteString("                    gear = {\n")
				if len(overallGear) > 0 {
					sb.WriteString("                        overall = {\n")
					for _, item := range overallGear {
						writeGearItem(&sb, item, "                            ")
					}
					sb.WriteString("                        },\n")
				}
				if len(raidGear) > 0 {
					sb.WriteString("                        raid = {\n")
					for _, item := range raidGear {
						writeGearItem(&sb, item, "                            ")
					}
					sb.WriteString("                        },\n")
				}
				if len(mythicGear) > 0 {
					sb.WriteString("                        mythicplus = {\n")
					for _, item := range mythicGear {
						writeGearItem(&sb, item, "                            ")
					}
					sb.WriteString("                        },\n")
				}
				sb.WriteString("                    },\n")

				// Enchants (including embellishments moved from gear)
				embEnchants := embellishmentsToEnchants(allEmbellishments)
				allEnchants := append(data.Enchants, embEnchants...)
				if len(allEnchants) > 0 {
					sb.WriteString("                    enchants = {\n")
					for _, ench := range allEnchants {
						sb.WriteString(fmt.Sprintf("                        { slot = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(ench.Slot), ench.ItemID, luaEscape(ench.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Gems
				if len(data.Gems) > 0 {
					sb.WriteString("                    gems = {\n")
					for _, gem := range data.Gems {
						sb.WriteString(fmt.Sprintf("                        { itemID = %d, name = \"%s\", note = \"%s\" },\n",
							gem.ItemID, luaEscape(gem.Name), luaEscape(gem.Note)))
					}
					sb.WriteString("                    },\n")
				}

				// Consumables
				if len(data.Consumables) > 0 {
					sb.WriteString("                    consumables = {\n")
					for _, cons := range data.Consumables {
						sb.WriteString(fmt.Sprintf("                        { type = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(cons.Type), cons.ItemID, luaEscape(cons.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Talents
				if len(data.TalentBuilds) > 0 {
					sb.WriteString("                    talents = {\n")
					for _, talent := range data.TalentBuilds {
						sb.WriteString(fmt.Sprintf("                        { name = \"%s\", code = \"%s\", context = \"%s\" },\n",
							luaEscape(talent.Name), luaEscape(talent.Code), luaEscape(talent.Context)))
					}
					sb.WriteString("                    },\n")
				}

				// Trinket Rankings
				if len(data.TrinketRankings) > 0 {
					sb.WriteString("                    trinketRankings = {\n")
					for _, tr := range data.TrinketRankings {
						sb.WriteString(fmt.Sprintf("                        { tier = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(tr.Tier), tr.ItemID, luaEscape(tr.Name)))
					}
					sb.WriteString("                    },\n")
				}

				sb.WriteString("                },\n")
			}

			sb.WriteString("            },\n")
		}

		sb.WriteString("        },\n")
	}

	sb.WriteString("    },\n")

	// Crest data (hardcoded per season - Midnight Season 1)
	sb.WriteString("    crests = {\n")
	sb.WriteString("        { name = \"Adventurer\", currencyID = 3383, cap = 500 },\n")
	sb.WriteString("        { name = \"Veteran\", currencyID = 3341, cap = 500 },\n")
	sb.WriteString("        { name = \"Champion\", currencyID = 3343, cap = 500 },\n")
	sb.WriteString("        { name = \"Hero\", currencyID = 3345, cap = 500 },\n")
	sb.WriteString("        { name = \"Myth\", currencyID = 3347, cap = 200 },\n")
	sb.WriteString("    },\n")

	// Upgrade track definitions (hardcoded per season)
	sb.WriteString("    upgradeTracks = {\n")
	sb.WriteString("        { name = \"Adventurer\", base = 220, top = 237, ranks = 6 },\n")
	sb.WriteString("        { name = \"Veteran\", base = 233, top = 250, ranks = 6 },\n")
	sb.WriteString("        { name = \"Champion\", base = 246, top = 263, ranks = 6 },\n")
	sb.WriteString("        { name = \"Hero\", base = 259, top = 276, ranks = 6 },\n")
	sb.WriteString("        { name = \"Myth\", base = 272, top = 289, ranks = 6 },\n")
	sb.WriteString("    },\n")

	sb.WriteString("}\n")

	// Write to AddOns folder
	addonDir := filepath.Join(addOnsPath, "ADHDBiS")
	if err := os.MkdirAll(addonDir, 0755); err != nil {
		return fmt.Errorf("creating addon directory: %w", err)
	}

	outputPath := filepath.Join(addonDir, "ADHDBiS_Data.lua")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing data file: %w", err)
	}

	fmt.Printf("Data written to: %s\n", outputPath)
	return nil
}
