package generator

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"adhdbis-updater/scraper"
)

// FetchLatestVersion checks GitHub for the latest release tag.
func FetchLatestVersion() string {
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get("https://api.github.com/repos/nenadjokic/ADHDBiS/releases/latest")
	if err != nil {
		return ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return ""
	}
	var result struct {
		TagName string `json:"tag_name"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return ""
	}
	// Strip leading "v" if present
	tag := result.TagName
	if len(tag) > 0 && tag[0] == 'v' {
		tag = tag[1:]
	}
	return tag
}

// luaEscape escapes a string for safe embedding in Lua source.
func luaEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}

// writeGearItem writes a single gear item entry to the string builder.
func writeGearItem(sb *strings.Builder, item scraper.GearItem, indent string) {
	sb.WriteString(fmt.Sprintf("%s{ slot = \"%s\", itemID = %d, name = \"%s\", source = \"%s\", bonusIDs = \"%s\", ilvl = %d",
		indent, luaEscape(item.Slot), item.ItemID, luaEscape(item.Name), luaEscape(item.Source), luaEscape(item.BonusIDs), item.Ilvl))
	if len(item.TooltipLines) > 0 {
		sb.WriteString(", tooltip = { ")
		for j, line := range item.TooltipLines {
			if j > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("\"%s\"", luaEscape(line)))
		}
		sb.WriteString(" }")
	}
	sb.WriteString(" },\n")
}

// GenerateLua creates ADHDBiS_Data.lua from scraped data and writes it to the AddOns folder.
func GenerateLua(allData map[string]map[string]map[string]*scraper.SpecData, addOnsPath string, source string) error {
	var sb strings.Builder

	sb.WriteString("-- ADHDBiS Data: Best in Slot lists for all classes\n")
	sb.WriteString(fmt.Sprintf("-- Generated by ADHDBiS Updater on %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("-- Source: %s\n\n", source))

	// Check GitHub for latest addon version
	latestVer := FetchLatestVersion()

	sb.WriteString("ADHDBiS_Data = {\n")
	sb.WriteString(fmt.Sprintf("    version = \"%s\",\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("    source = \"%s\",\n", luaEscape(source)))
	if latestVer != "" {
		sb.WriteString(fmt.Sprintf("    latestAddonVersion = \"%s\",\n", luaEscape(latestVer)))
	}
	sb.WriteString("    classes = {\n")

	for className, specs := range allData {
		sb.WriteString(fmt.Sprintf("        [\"%s\"] = {\n", luaEscape(className)))

		for specName, sources := range specs {
			sb.WriteString(fmt.Sprintf("            [\"%s\"] = {\n", luaEscape(specName)))

			for sourceName, data := range sources {
				sb.WriteString(fmt.Sprintf("                [\"%s\"] = {\n", luaEscape(sourceName)))

				// Gear
				sb.WriteString("                    gear = {\n")
				if len(data.RaidGear) > 0 {
					sb.WriteString("                        raid = {\n")
					for _, item := range data.RaidGear {
						writeGearItem(&sb, item, "                            ")
					}
					sb.WriteString("                        },\n")
				}
				if len(data.MythicGear) > 0 {
					sb.WriteString("                        mythicplus = {\n")
					for _, item := range data.MythicGear {
						writeGearItem(&sb, item, "                            ")
					}
					sb.WriteString("                        },\n")
				}
				sb.WriteString("                    },\n")

				// Enchants
				if len(data.Enchants) > 0 {
					sb.WriteString("                    enchants = {\n")
					for _, ench := range data.Enchants {
						sb.WriteString(fmt.Sprintf("                        { slot = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(ench.Slot), ench.ItemID, luaEscape(ench.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Gems
				if len(data.Gems) > 0 {
					sb.WriteString("                    gems = {\n")
					for _, gem := range data.Gems {
						sb.WriteString(fmt.Sprintf("                        { itemID = %d, name = \"%s\", note = \"%s\" },\n",
							gem.ItemID, luaEscape(gem.Name), luaEscape(gem.Note)))
					}
					sb.WriteString("                    },\n")
				}

				// Consumables
				if len(data.Consumables) > 0 {
					sb.WriteString("                    consumables = {\n")
					for _, cons := range data.Consumables {
						sb.WriteString(fmt.Sprintf("                        { type = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(cons.Type), cons.ItemID, luaEscape(cons.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Talents
				if len(data.TalentBuilds) > 0 {
					sb.WriteString("                    talents = {\n")
					for _, talent := range data.TalentBuilds {
						sb.WriteString(fmt.Sprintf("                        { name = \"%s\", code = \"%s\", context = \"%s\" },\n",
							luaEscape(talent.Name), luaEscape(talent.Code), luaEscape(talent.Context)))
					}
					sb.WriteString("                    },\n")
				}

				// Trinket Rankings
				if len(data.TrinketRankings) > 0 {
					sb.WriteString("                    trinketRankings = {\n")
					for _, tr := range data.TrinketRankings {
						sb.WriteString(fmt.Sprintf("                        { tier = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(tr.Tier), tr.ItemID, luaEscape(tr.Name)))
					}
					sb.WriteString("                    },\n")
				}

				sb.WriteString("                },\n")
			}

			sb.WriteString("            },\n")
		}

		sb.WriteString("        },\n")
	}

	sb.WriteString("    },\n")
	sb.WriteString("}\n")

	// Write to AddOns folder
	addonDir := filepath.Join(addOnsPath, "ADHDBiS")
	if err := os.MkdirAll(addonDir, 0755); err != nil {
		return fmt.Errorf("creating addon directory: %w", err)
	}

	outputPath := filepath.Join(addonDir, "ADHDBiS_Data.lua")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing data file: %w", err)
	}

	fmt.Printf("Data written to: %s\n", outputPath)
	return nil
}
