package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"adhdbis-updater/scraper"
)

// luaEscape escapes a string for safe embedding in Lua source.
func luaEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}

// GenerateLua creates ADHDBiS_Data.lua from scraped data and writes it to the AddOns folder.
func GenerateLua(allData map[string]map[string]map[string]*scraper.SpecData, addOnsPath string, source string) error {
	var sb strings.Builder

	sb.WriteString("-- ADHDBiS Data: Best in Slot lists for all classes\n")
	sb.WriteString(fmt.Sprintf("-- Generated by ADHDBiS Updater on %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("-- Source: %s\n\n", source))

	sb.WriteString("ADHDBiS_Data = {\n")
	sb.WriteString(fmt.Sprintf("    version = \"%s\",\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("    source = \"%s\",\n", luaEscape(source)))
	sb.WriteString("    classes = {\n")

	for className, specs := range allData {
		sb.WriteString(fmt.Sprintf("        [\"%s\"] = {\n", luaEscape(className)))

		for specName, sources := range specs {
			sb.WriteString(fmt.Sprintf("            [\"%s\"] = {\n", luaEscape(specName)))

			for sourceName, data := range sources {
				sb.WriteString(fmt.Sprintf("                [\"%s\"] = {\n", luaEscape(sourceName)))

				// Gear
				sb.WriteString("                    gear = {\n")
				if len(data.RaidGear) > 0 {
					sb.WriteString("                        raid = {\n")
					for _, item := range data.RaidGear {
						sb.WriteString(fmt.Sprintf("                            { slot = \"%s\", itemID = %d, name = \"%s\", source = \"%s\", bonusIDs = \"%s\", ilvl = %d },\n",
							luaEscape(item.Slot), item.ItemID, luaEscape(item.Name), luaEscape(item.Source), luaEscape(item.BonusIDs), item.Ilvl))
					}
					sb.WriteString("                        },\n")
				}
				if len(data.MythicGear) > 0 {
					sb.WriteString("                        mythicplus = {\n")
					for _, item := range data.MythicGear {
						sb.WriteString(fmt.Sprintf("                            { slot = \"%s\", itemID = %d, name = \"%s\", source = \"%s\", bonusIDs = \"%s\", ilvl = %d },\n",
							luaEscape(item.Slot), item.ItemID, luaEscape(item.Name), luaEscape(item.Source), luaEscape(item.BonusIDs), item.Ilvl))
					}
					sb.WriteString("                        },\n")
				}
				sb.WriteString("                    },\n")

				// Enchants
				if len(data.Enchants) > 0 {
					sb.WriteString("                    enchants = {\n")
					for _, ench := range data.Enchants {
						sb.WriteString(fmt.Sprintf("                        { slot = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(ench.Slot), ench.ItemID, luaEscape(ench.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Gems
				if len(data.Gems) > 0 {
					sb.WriteString("                    gems = {\n")
					for _, gem := range data.Gems {
						sb.WriteString(fmt.Sprintf("                        { itemID = %d, name = \"%s\", note = \"%s\" },\n",
							gem.ItemID, luaEscape(gem.Name), luaEscape(gem.Note)))
					}
					sb.WriteString("                    },\n")
				}

				// Consumables
				if len(data.Consumables) > 0 {
					sb.WriteString("                    consumables = {\n")
					for _, cons := range data.Consumables {
						sb.WriteString(fmt.Sprintf("                        { type = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(cons.Type), cons.ItemID, luaEscape(cons.Name)))
					}
					sb.WriteString("                    },\n")
				}

				// Talents
				if len(data.TalentBuilds) > 0 {
					sb.WriteString("                    talents = {\n")
					for _, talent := range data.TalentBuilds {
						sb.WriteString(fmt.Sprintf("                        { name = \"%s\", code = \"%s\", context = \"%s\" },\n",
							luaEscape(talent.Name), luaEscape(talent.Code), luaEscape(talent.Context)))
					}
					sb.WriteString("                    },\n")
				}

				// Trinket Rankings
				if len(data.TrinketRankings) > 0 {
					sb.WriteString("                    trinketRankings = {\n")
					for _, tr := range data.TrinketRankings {
						sb.WriteString(fmt.Sprintf("                        { tier = \"%s\", itemID = %d, name = \"%s\" },\n",
							luaEscape(tr.Tier), tr.ItemID, luaEscape(tr.Name)))
					}
					sb.WriteString("                    },\n")
				}

				sb.WriteString("                },\n")
			}

			sb.WriteString("            },\n")
		}

		sb.WriteString("        },\n")
	}

	sb.WriteString("    },\n")
	sb.WriteString("}\n")

	// Write to AddOns folder
	addonDir := filepath.Join(addOnsPath, "ADHDBiS")
	if err := os.MkdirAll(addonDir, 0755); err != nil {
		return fmt.Errorf("creating addon directory: %w", err)
	}

	outputPath := filepath.Join(addonDir, "ADHDBiS_Data.lua")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing data file: %w", err)
	}

	fmt.Printf("Data written to: %s\n", outputPath)
	return nil
}
